replicaCount: 2

image:
  repository: 192.168.83.200:8888/cicd-demo/app
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: harbor-secret

service:
  type: NodePort
  port: 5000
  nodePort: 30001

resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "128Mi"
    cpu: "100m"

livenessProbe:
  httpGet:
    path: /health
    port: 5000
  initialDelaySeconds: 5
  periodSeconds: 10
